<?php
/**
 * admin/extract-client-pdf.php
 * Receives a PDF upload and returns extracted text as JSON.
 * Pure PHP — no Composer, no external binaries required.
 */
require_once __DIR__ . '/../bootstrap.php';
requireRole(['admin', 'buyer']);

header('Content-Type: application/json; charset=utf-8');

try {
    if (empty($_FILES['pdf']) || $_FILES['pdf']['error'] !== UPLOAD_ERR_OK) {
        $code = $_FILES['pdf']['error'] ?? -1;
        echo json_encode(['success' => false, 'error' => 'Upload error code ' . $code]);
        exit;
    }

    $tmp  = $_FILES['pdf']['tmp_name'];
    $name = $_FILES['pdf']['name'];
    $size = $_FILES['pdf']['size'];

    // Basic validation
    if ($size > 20 * 1024 * 1024) {
        echo json_encode(['success' => false, 'error' => 'File too large (max 20 MB).']);
        exit;
    }

    // Verify PDF magic bytes
    $fh  = fopen($tmp, 'rb');
    $sig = fread($fh, 4);
    fclose($fh);
    if ($sig !== '%PDF') {
        echo json_encode(['success' => false, 'error' => 'File does not appear to be a PDF.']);
        exit;
    }

    $text = extractPdfText($tmp);

    echo json_encode([
        'success' => true,
        'text'    => $text,
        'pages'   => 0,   // page count not needed for field parsing
        'chars'   => strlen($text),
    ]);

} catch (Throwable $e) {
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
}

// ---------------------------------------------------------------------------
// Pure-PHP PDF text extractor
// Handles FlateDecode compressed streams and raw/uncompressed text streams.
// Works with PDFs generated by Word, Acrobat, LibreOffice, etc.
// ---------------------------------------------------------------------------
function extractPdfText(string $path): string
{
    $raw = file_get_contents($path);
    if ($raw === false) {
        throw new RuntimeException('Could not read file.');
    }

    $text = '';

    // ── 1. Try compressed (FlateDecode) streams ──────────────────────────
    preg_match_all('/stream\r?\n(.*?)\r?\nendstream/s', $raw, $streams);
    foreach ($streams[1] as $stream) {
        // Strip leading whitespace/CR that confuses gzuncompress
        $stream = ltrim($stream);
        $decompressed = @gzuncompress($stream);
        if ($decompressed === false) {
            // Try with a zlib wrapper offset
            $decompressed = @gzinflate(substr($stream, 2));
        }
        if ($decompressed !== false) {
            $text .= extractTextOps($decompressed) . "\n";
        }
    }

    // ── 2. Raw / uncompressed BT...ET blocks ────────────────────────────
    preg_match_all('/BT\b(.*?)\bET/s', $raw, $btBlocks);
    foreach ($btBlocks[1] as $block) {
        $text .= extractTextOps($block) . "\n";
    }

    // ── 3. Fallback: grab anything in parentheses near Tj/TJ operators ──
    if (trim($text) === '') {
        preg_match_all('/\(([^)]{1,300})\)\s*Tj/s', $raw, $fallback);
        foreach ($fallback[1] as $s) {
            $text .= pdfStringDecode($s) . ' ';
        }
    }

    // Normalise whitespace
    $text = preg_replace('/[ \t]+/', ' ', $text);
    $text = preg_replace('/\n{3,}/', "\n\n", $text);
    return trim($text);
}

// Extract text from a decoded PDF content stream
function extractTextOps(string $stream): string
{
    $out = '';

    // Tj — show single string:  (Hello) Tj
    preg_match_all('/\(([^)\\\\]*(?:\\\\.[^)\\\\]*)*)\)\s*Tj/s', $stream, $m1);
    foreach ($m1[1] as $s) {
        $out .= pdfStringDecode($s) . ' ';
    }

    // TJ — show array of strings:  [(Hello) -200 (World)] TJ
    preg_match_all('/\[([^\]]*)\]\s*TJ/s', $stream, $m2);
    foreach ($m2[1] as $arr) {
        preg_match_all('/\(([^)\\\\]*(?:\\\\.[^)\\\\]*)*)\)/', $arr, $parts);
        foreach ($parts[1] as $s) {
            $out .= pdfStringDecode($s);
        }
        $out .= ' ';
    }

    // Td / T* / Tm — treat as newlines between text positions
    $out = preg_replace('/\bT[dD*m]\b/', "\n", $out);

    return $out;
}

// Decode common PDF string escape sequences
function pdfStringDecode(string $s): string
{
    $s = str_replace(['\\n', '\\r', '\\t'], ["\n", "\r", "\t"], $s);
    $s = preg_replace_callback('/\\\\([0-7]{1,3})/', function ($m) {
        return chr(octdec($m[1]));
    }, $s);
    $s = str_replace(['\\(', '\\)', '\\\\'], ['(', ')', '\\'], $s);
    // Strip non-printable chars except whitespace
    $s = preg_replace('/[^\x09\x0A\x0D\x20-\x7E]/', '', $s);
    return $s;
}
